apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
- prometheus/templates/server/clusterrole.yaml
- prometheus/templates/server/clusterrolebinding.yaml
- prometheus/templates/server/deploy.yaml
- prometheus/templates/server/cm.yaml
- prometheus/templates/server/service.yaml
- prometheus/templates/server/serviceaccount.yaml
- prometheus/templates/node-exporter/daemonset.yaml
- prometheus/templates/node-exporter/serviceaccount.yaml
- prometheus/templates/node-exporter/svc.yaml
- prometheus/templates/alertmanager/cm.yaml
- prometheus/templates/alertmanager/deploy.yaml
- prometheus/templates/alertmanager/service.yaml
- prometheus/templates/alertmanager/serviceaccount.yaml
